language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - sudo apt-get update
install:
  - pip install --upgrade setuptools
  - pip install -U -r requirements.txt
  - python setup.py install
script:
  - pytest tests
after_success:
  - coveralls